### ISSUE TITLE
Conversion large file xml to json does nothing

### ISSUE THREAD

**Issue by HilaryGreen** [laggery/vscode-fhir-tools#7] opened 2020-06-04 14:18 UTC
Trying to convert a large FHIR file from xml to json. It is 100MB (because it contains base64 encoded documents). Is there a limitation on the size which can be converted?

(The conversion does nothing - no message, no conversion)

**Comment by laggery** [comment] 2020-06-12 19:58
Hello @HilaryGreen 

Thanks for your issue.

Actually I never tried to convert such a big File. I think the limitation is the max size that VSCode can open, but I’m not sure.

Have you tried with VSCode? What error did you get?

I didn’t write the conversion algorithm. For that I used the following open source Project: https://github.com/lantanagroup/FHIR.js

Let me know if I can do something or close this issue.

Best regards 
Yannick

**Comment by laggery** [comment] 2020-11-12 12:13
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the latest version.
You can also contribute directly by providing a patch.

Thank you!

**Closed as completed by laggery** 2020-11-12 12:13 UTC
